apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: gremlin-workshop
spec:
  selector: { app: api-gateway }
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: gremlin-workshop
spec:
  selector: { app: payments }
  ports:
    - name: http
      port: 3001
      targetPort: 3001
